//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginCodeFirst.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CategoryResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CategoryResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("LoginCodeFirst.Resources.CategoryResources", typeof(CategoryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string lbl_ListCategory {
            get {
                return ResourceManager.GetString("lbl_ListCategory", resourceCulture);
            }
        }
        
        public static string lbl_CategoryName {
            get {
                return ResourceManager.GetString("lbl_CategoryName", resourceCulture);
            }
        }
        
        public static string lbl_AddCategory {
            get {
                return ResourceManager.GetString("lbl_AddCategory", resourceCulture);
            }
        }
        
        public static string lbl_EditCategory {
            get {
                return ResourceManager.GetString("lbl_EditCategory", resourceCulture);
            }
        }
        
        public static string err_AddCategoryFailure {
            get {
                return ResourceManager.GetString("err_AddCategoryFailure", resourceCulture);
            }
        }
        
        public static string err_EditCategoryFailure {
            get {
                return ResourceManager.GetString("err_EditCategoryFailure", resourceCulture);
            }
        }
    }
}
