//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginCodeFirst.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("LoginCodeFirst.Resources.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string btn_Add {
            get {
                return ResourceManager.GetString("btn_Add", resourceCulture);
            }
        }
        
        public static string btn_Edit {
            get {
                return ResourceManager.GetString("btn_Edit", resourceCulture);
            }
        }
        
        public static string btn_Delete {
            get {
                return ResourceManager.GetString("btn_Delete", resourceCulture);
            }
        }
        
        public static string btn_Submit {
            get {
                return ResourceManager.GetString("btn_Submit", resourceCulture);
            }
        }
        
        public static string btn_ComBack {
            get {
                return ResourceManager.GetString("btn_ComBack", resourceCulture);
            }
        }
        
        public static string lbl_Actions {
            get {
                return ResourceManager.GetString("lbl_Actions", resourceCulture);
            }
        }
        
        public static string btn_YouDelete {
            get {
                return ResourceManager.GetString("btn_YouDelete", resourceCulture);
            }
        }
        
        public static string lbl_NumbericalOrder {
            get {
                return ResourceManager.GetString("lbl_NumbericalOrder", resourceCulture);
            }
        }
        
        public static string msg_AlreadyExists {
            get {
                return ResourceManager.GetString("msg_AlreadyExists", resourceCulture);
            }
        }
        
        public static string msg_NotEmpty {
            get {
                return ResourceManager.GetString("msg_NotEmpty", resourceCulture);
            }
        }
        
        public static string msg_8Characters {
            get {
                return ResourceManager.GetString("msg_8Characters", resourceCulture);
            }
        }
        
        public static string msg_LettersAndNumbers {
            get {
                return ResourceManager.GetString("msg_LettersAndNumbers", resourceCulture);
            }
        }
        
        public static string msg_AValidEmail {
            get {
                return ResourceManager.GetString("msg_AValidEmail", resourceCulture);
            }
        }
        
        public static string msg_WithALetter {
            get {
                return ResourceManager.GetString("msg_WithALetter", resourceCulture);
            }
        }
        
        public static string msg_AddSuccess {
            get {
                return ResourceManager.GetString("msg_AddSuccess", resourceCulture);
            }
        }
        
        public static string msg_DeleteSuccess {
            get {
                return ResourceManager.GetString("msg_DeleteSuccess", resourceCulture);
            }
        }
        
        public static string msg_EditSuccess {
            get {
                return ResourceManager.GetString("msg_EditSuccess", resourceCulture);
            }
        }
        
        public static string msg_DeleteError {
            get {
                return ResourceManager.GetString("msg_DeleteError", resourceCulture);
            }
        }
    }
}
