//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginCodeFirst.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProductResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("LoginCodeFirst.Resources.ProductResources", typeof(ProductResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string lbl_ListProduct {
            get {
                return ResourceManager.GetString("lbl_ListProduct", resourceCulture);
            }
        }
        
        public static string lbl_ProductName {
            get {
                return ResourceManager.GetString("lbl_ProductName", resourceCulture);
            }
        }
        
        public static string lbl_BrandId {
            get {
                return ResourceManager.GetString("lbl_BrandId", resourceCulture);
            }
        }
        
        public static string lbl_CategoryId {
            get {
                return ResourceManager.GetString("lbl_CategoryId", resourceCulture);
            }
        }
        
        public static string lbl_ModelYear {
            get {
                return ResourceManager.GetString("lbl_ModelYear", resourceCulture);
            }
        }
        
        public static string lbl_ListPrice {
            get {
                return ResourceManager.GetString("lbl_ListPrice", resourceCulture);
            }
        }
        
        public static string lbl_Image {
            get {
                return ResourceManager.GetString("lbl_Image", resourceCulture);
            }
        }
        
        public static string lbl_EditProduct {
            get {
                return ResourceManager.GetString("lbl_EditProduct", resourceCulture);
            }
        }
        
        public static string lbl_AddProduct {
            get {
                return ResourceManager.GetString("lbl_AddProduct", resourceCulture);
            }
        }
        
        public static string err_AddProductFailure {
            get {
                return ResourceManager.GetString("err_AddProductFailure", resourceCulture);
            }
        }
        
        public static string err_EditProductFailure {
            get {
                return ResourceManager.GetString("err_EditProductFailure", resourceCulture);
            }
        }
    }
}
