//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginCodeFirst.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StoreResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StoreResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("LoginCodeFirst.Resources.StoreResources", typeof(StoreResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string lbl_ListStore {
            get {
                return ResourceManager.GetString("lbl_ListStore", resourceCulture);
            }
        }
        
        public static string lbl_StoreName {
            get {
                return ResourceManager.GetString("lbl_StoreName", resourceCulture);
            }
        }
        
        public static string lbl_Street {
            get {
                return ResourceManager.GetString("lbl_Street", resourceCulture);
            }
        }
        
        public static string lbl_City {
            get {
                return ResourceManager.GetString("lbl_City", resourceCulture);
            }
        }
        
        public static string lbl_State {
            get {
                return ResourceManager.GetString("lbl_State", resourceCulture);
            }
        }
        
        public static string lbl_ZipCode {
            get {
                return ResourceManager.GetString("lbl_ZipCode", resourceCulture);
            }
        }
        
        public static string lbl_EditStore {
            get {
                return ResourceManager.GetString("lbl_EditStore", resourceCulture);
            }
        }
        
        public static string lbl_AddStore {
            get {
                return ResourceManager.GetString("lbl_AddStore", resourceCulture);
            }
        }
        
        public static string lbl_Phone {
            get {
                return ResourceManager.GetString("lbl_Phone", resourceCulture);
            }
        }
        
        public static string lbl_Email {
            get {
                return ResourceManager.GetString("lbl_Email", resourceCulture);
            }
        }
        
        public static string err_AddStoreFailure {
            get {
                return ResourceManager.GetString("err_AddStoreFailure", resourceCulture);
            }
        }
        
        public static string err_EditStoreFailure {
            get {
                return ResourceManager.GetString("err_EditStoreFailure", resourceCulture);
            }
        }
    }
}
