//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginCodeFirst.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("LoginCodeFirst.Resources.UserResources", typeof(UserResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string lbl_StoreId {
            get {
                return ResourceManager.GetString("lbl_StoreId", resourceCulture);
            }
        }
        
        public static string lbl_FullName {
            get {
                return ResourceManager.GetString("lbl_FullName", resourceCulture);
            }
        }
        
        public static string lbl_IsActive {
            get {
                return ResourceManager.GetString("lbl_IsActive", resourceCulture);
            }
        }
        
        public static string lbl_ListUser {
            get {
                return ResourceManager.GetString("lbl_ListUser", resourceCulture);
            }
        }
        
        public static string lbl_EditUser {
            get {
                return ResourceManager.GetString("lbl_EditUser", resourceCulture);
            }
        }
        
        public static string lbl_AddUser {
            get {
                return ResourceManager.GetString("lbl_AddUser", resourceCulture);
            }
        }
        
        public static string lbl_ZipCode {
            get {
                return ResourceManager.GetString("lbl_ZipCode", resourceCulture);
            }
        }
        
        public static string lbl_Phone {
            get {
                return ResourceManager.GetString("lbl_Phone", resourceCulture);
            }
        }
        
        public static string lbl_Email {
            get {
                return ResourceManager.GetString("lbl_Email", resourceCulture);
            }
        }
        
        public static string lbl_Password {
            get {
                return ResourceManager.GetString("lbl_Password", resourceCulture);
            }
        }
        
        public static string lbl_EditPassword {
            get {
                return ResourceManager.GetString("lbl_EditPassword", resourceCulture);
            }
        }
        
        public static string lbl_NewPassword {
            get {
                return ResourceManager.GetString("lbl_NewPassword", resourceCulture);
            }
        }
        
        public static string lbl_ConfirmPassword {
            get {
                return ResourceManager.GetString("lbl_ConfirmPassword", resourceCulture);
            }
        }
        
        public static string msg_ConfirmPasswordMustBeEqualNewPassword {
            get {
                return ResourceManager.GetString("msg_ConfirmPasswordMustBeEqualNewPassword", resourceCulture);
            }
        }
        
        public static string btn_Close {
            get {
                return ResourceManager.GetString("btn_Close", resourceCulture);
            }
        }
        
        public static string btn_Save {
            get {
                return ResourceManager.GetString("btn_Save", resourceCulture);
            }
        }
        
        public static string msg_EditPasswordSuccess {
            get {
                return ResourceManager.GetString("msg_EditPasswordSuccess", resourceCulture);
            }
        }
        
        public static string err_EditPasswordFailure {
            get {
                return ResourceManager.GetString("err_EditPasswordFailure", resourceCulture);
            }
        }
        
        public static string err_EditUserFailure {
            get {
                return ResourceManager.GetString("err_EditUserFailure", resourceCulture);
            }
        }
        
        public static string err_AddUserFailure {
            get {
                return ResourceManager.GetString("err_AddUserFailure", resourceCulture);
            }
        }
        
        public static string err_LoginFailure {
            get {
                return ResourceManager.GetString("err_LoginFailure", resourceCulture);
            }
        }
        
        public static string btn_EditPassword {
            get {
                return ResourceManager.GetString("btn_EditPassword", resourceCulture);
            }
        }
        
        public static string lbl_Role {
            get {
                return ResourceManager.GetString("lbl_Role", resourceCulture);
            }
        }
    }
}
